### ISSUE TITLE
error on diffcyt

### ISSUE THREAD

**Issue by mimisikai** [lmweber/diffcyt#13]
I encounter this error occurs repeatedly. And I have not clue on the limited error message. 
Can you advice some inputs? 

> res_DS_2vs1 = diffcyt(CD154_sce_SCIT, clustering_to_use = "meta20",
+                        analysis_type = "DS", method_DS = "diffcyt-DS-limma",
+                        design = design, contrast = contrast2vs1)
using SingleCellExperiment object from CATALYST as input
using cluster IDs from clustering stored in column 'meta20' of 'cluster_codes' data frame in 'metadata' of SingleCellExperiment object from CATALYST
calculating features...
Error in calcMedians(d_se) : 
  all(sapply(medians, function(m) { .... is not TRUE

**Comment by markrobinsonuzh** [comment]
The code snippet where this error is thrown (`calcMedians`) is this:
```
    stopifnot(all(sapply(medians, function(m) {
        col_data$sample_id == colnames(m)
    })))
```

I have a suspicion that this error is related to the unique sample names problems you had here:
https://github.com/HelenaLC/CATALYST/issues/85

Otherwise, we need more details.
