### ISSUE TITLE
Error running differential analysis on diffcyt

### ISSUE THREAD

**Issue by FedericaOrsenigo** [lmweber/diffcyt#14]
I am currently following a CyTOF workflow in order to analyse CyTOF  datas with CATALYST package and diffcyt package; however I keep getting the same error and I don't understand where it comes from.
Everything works just fine until I try to create the object "ds_res1".
```
> ds_res1 <- diffcyt(sce, 
+                    formula = ds_formula1, contrast = contrast,
+                    analysis_type = "DS", method_DS = "diffcyt-DS-LMM",
+                    clustering_to_use = "merging1", verbose = FALSE)
```

I always get this error:
`Error in rep(NA, nrow(meds)) : invalid 'times' argument`.

I am new to R and I don't know what "times" means in this case.

Thanks for your time.
I will be grateful if you could comment on this.

**Comment by markrobinsonuzh** [comment]
I'm going to take a guess that it's because you have no state markers (i.e., all markers are annotated as type markers).

Can you give the following details?

- output of `sessionInfo()`
- after you get the error, give the output of traceback()
- output of `state_markers(sce)`

**Comment by leeanapeters** [comment]
I am having the same issue though differential abundance ran fine. Do I need to reassign the markers I want assessed as "state"? They are currently all "type".


Thanks!


Leeana

**Comment by markrobinsonuzh** [comment]
Ideally, there is an actual split of type (e.g., cell surface markers) and state (e.g., cytokines, etc.) markers, but it's not always clear how to do that. I just worry that if you've clustered on all markers, then there may not really be a differential state analysis to do.

Re: running `diffcyt()`, reassigning the `marker_class` column to `state` could work. Note that `diffcyt()` also has a `markers_to_test` argument. See `?diffcyt`.
