### ISSUE TITLE
Manual gating input for DA clusters

### ISSUE THREAD

**Issue by EAC-T** [lmweber/diffcyt#33]
Hi All,

I have Cytof data, instead of doing unsupervised clustering, I found that manual gating made more sense and allowed me to find more subsets. I know have the cell subsets for each individual in an excel sheet, row(Individual) col(Cell subsets). is it possible that I use this as an input to the DA test?

Thank you a lot,

**Comment by markrobinsonuzh** [comment]
@EAC-T I think the most direct way would be to use the `testDA_edgeR()` function. It would require you to re-format your excel sheet into a `SummarizedExperiment` object, *where rows = clusters, columns = samples, assay = values (counts).* (see `?diffcyt::calcCounts`). You can also read the docs here: `?diffcyt::testDA_edgeR`.
