### ISSUE TITLE
error with wrapper diffcyt() function

### ISSUE THREAD

**Issue by jenkinmt** [lmweber/diffcyt#35]
Hey, 
I am encountering this error when using the wrapper function:

Error in diffcyt(da_input = "d_flowSet", experiment_info = read.csv("21_8_6_metadata_mouseid_MTJ.csv"),  : 
  unused argument (da_input = "d_flowSet")

Here is my input code: diffcyt(da_input = "d_flowSet", experiment_info = read.csv("21_8_6_metadata_mouseid_MTJ.csv"), marker_info = read.csv("21_8_6_tet2ko_panel_metadata_MTJ"))

**Comment by jenkinmt** [comment]
update: this has been solved I believed. however, I am now encountering an error with the prepareData function. Here is my code:
prepareData(d_input = d_flowSet, experiment_info = data.frame1, marker_info = data.frame2)
Where data.frame1 = a .csv file I read in containing group_id and sample_id cols for my individuals in dataset
and data.frame2 = a .csv containing the cols marker_name and marker_class which I believe are the required names for this input for marker_info. My error is this:
Error in if (!(nrow(marker_info) == ncol(d_ex[[1]]))) { : 
  argument is of length zero

It appears to be telling me that the function is calling on a non-existent col of data in my .csv, even though my .csv contains only the required information of marker_name and marker_class

**Comment by HelenaLC** [comment]
Please post this [here](https://github.com/HelenaLC/CATALYST/issues) instead, as it's `CATALYST` no 'diffcyt' related.
