### ISSUE TITLE
issue with setting up design/contrast matrices for DA/DS testing with catalyst SCE 

### ISSUE THREAD

**Issue by jenkinmt** [lmweber/diffcyt#36]
Hi,
I've been working through the analysis pipelines for catalyst and diffcyt, and had some questions with setting up the design and contrast matrices. For my particular code, I am feeding an sce from catalyst in to the diffcyt wrapper and am using the code below to generate my design and contrast. Here, patient_id is equal to the genotype of my mice (wt vs KO). 
```
design <- createDesignMatrix(ei(sce), cols_design = c("patient_id"))
contrast <- createContrast(c(1,0))```
The pic below shows the design matrix this produced:
![image](https://user-images.githubusercontent.com/77988339/129968898-e6497e4a-a740-47a2-b103-c2ebe368d540.png).
The first three 1's correspond to the rows in my metadata for the mice where the 1s are for WT mice and 0s are for KO mice. Then, would I not set up my contrast to be c(1,0) since that is how the numbers are ordered in my design matrix? Such that this would compare wt vs KO? or would I order the contrast as c(0,1)? 

Thanks for your help!
Matt Jenkins

**Comment by markrobinsonuzh** [comment]
Hi Matt,

The image didn't render well in the thread, but basically your design matrix is this:
```
  (Intercept) zwildtype
1           1         1
2           1         1
3           1         1
4           1         0
5           1         0
6           1         0
```

In this case, a contrast `c(0,1)` would test wildtype-KO .. or a contrast `c(0,-1)` would test KO-wildtype (I think the latter is more natural).

Does that answer your question?

**Comment by jenkinmt** [comment]
Hi Mark,
Thanks for your fast response! Yes, I believe that does answer my question! 
Matt
